title: 2nd Seminar on Artificial Intelligence applied to Sound and Music Composition
description: Tokyo University of the Arts, 15th of January 2020.

In collaboration with,

* The University of Tokyo

* IRCAM (Paris, France - Institut de Recherche et Coordination Acoustique/Musique).

theme: jekyll-theme-slate
